install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run 'docker build -t brettbj/daps-base . && docker run brettbj/daps-base echo Built Daps-base'
  - which python
  - nose2 --plugin nose2.plugins.junitxml --junit-xml test 
  - mv nose2-junit.xml shippable/testresults/tests.xml
  - jupyter nbconvert --to html ./visualize/Figures.ipynb
  - cp Figures.html shippable/buildoutput/
  - coverage run --branch test.py
  - coverage xml -o shippable/codecoverage/coverage.xml test.py